# Basic Information
title: Xiwei Deng
position: M.S.
first_department: Institute of Artificial Intelligence
first_department_link: https://iai.xmu.edu.cn/
second_department: Fujian Provincial Key Laboratory of Plasma and Magnetic Resonance
second_department_link: https://pmr.xmu.edu.cn/index.htm
affiliation: Xiamen University (XMU)
affiliation_link: https://www.xmu.edu.cn/
address: Xiamen, Fujian, China
email: xiweideng@stu.xmu.edu.cn
modification_date: Aug 2023
# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Your name
description: The description
canonical: https://jekyll-jemdoc.yliu.me/

# Links
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/
github: https://github.com/xiweideng
research_gate: https://www.researchgate.net/profile/Xiwei-Deng-2
orcid: javascript:;
linkedin: javascript:;
twitter: javascript:;
facebook: javascript:;
# Images (e.g., your profile picture and your website's favicon)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon-caltech.png
favicon_dark: ./assets/img/favicon-caltech.png

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - jekyll-jemdoc.gemspec
